### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by tangentstorm** [toomasv/drawing#1]
Hi @toomasv ! 
This drawing tool is great!
It seems to (mostly?) work on red 0.6.4 in windows after turning off the `systme/state/trace: 20` line.

But... is it available under some kind of open source license?

**Comment by toomasv** [comment]
Hi, @tangentstorm!
Thanks for your interest! I wrote this when learning Red and haven't updated it since, thus many things may be broken. Be free to do whatever you want with it. I added license as you asked.

**Comment by tangentstorm** [comment]
Thanks so much!
